# Generated by Django 5.0.7 on 2024-07-15 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='session_year',
            new_name='session_year_id',
        ),
    ]
