# Generated by Django 5.0.7 on 2024-07-18 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_attendace_attendancereport'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attendace',
            new_name='Attendance',
        ),
    ]
